//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfComputerServiceApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Computer
    {
        public int ID { get; set; }
        public string CompanyName { get; set; }
        public int IDComputerType { get; set; }
        public int IDCooler { get; set; }
        public int IDMotherboard { get; set; }
        public int IDStorageDevice { get; set; }
        public int IDPowerUnit { get; set; }
        public int IDCPU { get; set; }
        public int IDVideoCard { get; set; }
        public string Photo { get; set; }
    
        public virtual ComputerType ComputerType { get; set; }
        public virtual Cooler Cooler { get; set; }
        public virtual CPU CPU { get; set; }
        public virtual Motherboard Motherboard { get; set; }
        public virtual PowerUnit PowerUnit { get; set; }
        public virtual StorageDevice StorageDevice { get; set; }
        public virtual VideoCard VideoCard { get; set; }
    }
}
